name: mi-adf-shir
trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: cnp-library
    type: github
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts'

jobs:
- job: Release
  # Make sure we have a tag to run this job
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
 
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: steps/charts/release.yaml@cnp-library
    parameters:
      chartName: mi-adf-shir
      chartReleaseName: mi-adf-shir
      chartNamespace: chart-tests
      acrName: "hmctspublic"
      chartPath: "./charts/"
